### PR TITLE
Adds to define if defaults are applied to config loader.

### PR DESCRIPTION
**Pull request by frederic-kneier**

### CODE REVIEW

**Comment by sksamuel** [comment]
There are no tests, so I don't know what the purpose of this change is ?

**Comment by frederic-kneier** [comment]
The main idea is to optionally create a config loader without the predefined sources, preprocessors or mappers. I will try to add additional test cases

**Comment by frederic-kneier** [comment]
Are the supplied tests ok?

**Comment by sksamuel** [comment]
Looks great

**Pull request merged**
