### PR TITLE
Kotlin AWS sdk

### PR DESCRIPTION
**Pull request by samu-developments**
We had a use case similar to this https://github.com/aws/aws-sdk-java-v2/issues/4501#issuecomment-1774988695; testing with Localstack and overriding AWS sdk endpoints using env variables. This is for some reason not supported in Java sdks, but it is in Kotlin sdks. 

This PR is a copy of the `hoplite-aws` module, with java aws sdk switched with kotlin sdk. Also updated kotlin version and updated some usage of version catalogs, gradle. 

I will have this as draft until [this](https://github.com/sksamuel/hoplite/pull/423) has feedback

Kotlin version needed to be updated for the newest Kotlin aws sdk to be compatible `> The binary version of its metadata is 1.9.0, expected version is 1.6.0.`
Also fixed kotlin test tasks needing jdk 11 (required by testcontainers). `> Inconsistent JVM-target compatibility detected for tasks 'compileTestJava' (11) and 'compileTestKotlin' (1.8).`

### CODE REVIEW

**Comment by sarahzargari** [comment]
@sksamuel any updates on when this might move past draft status?

**Comment by samu-developments** [comment]
I can take a look at it next week again

**Comment by samu-developments** [comment]
Look at that, now the java sdk contains the env variable endpoint override. Anyway I rebased the branch and will make it ready for review.

**Review by sksamuel — APPROVED** [review]

**Comment by sksamuel** [comment]
> @sksamuel any updates on when this might move past draft status?

2.9.0 is now released !

**Pull request merged**
