### PR TITLE
Hide fp classes

### PR DESCRIPTION
**Pull request by sksamuel**
@Kantis my only concern with this approach is that anyone who wants to do a custom decoder has to import the hoplite-fp module themselves.

### CODE REVIEW

**Comment by Kantis** [comment]
Right. So it's a breaking change for users who have already done so. Not that hard to fix though 🙂 I think most users aren't writing custom decoders, so for them it'll be an improvement that might still motivate the change?

**Comment by sksamuel** [comment]
I'm more just concerned that it seems odd. To implement a decoder you have to also import an "invisible" library. Strange?

**Comment by Kantis** [comment]
Yeah, you're right. Perhaps it could be remedied by clear docs and naming? Maybe something like `hoplite-decoder` makes more sense than `hoplite-fp`, even if it's a wrapper around functional programming constructs.

**Comment by sksamuel** [comment]
Maybe another solution is to just rename Hoplite's Validated to something else, so people won't try to use it.

**Comment by Kantis** [comment]
Yeah, that could be a pragmatic approach. Or we could just live with it.. I just accidentally imported `Either.Right` from AWS SDK as well. 🤡

**Comment by sksamuel** [comment]
I guess if you set hoplite to implementation where you use it, then you only see the classes in that one place. Most of your modules should depend on your config classes not hoplite.

**Pull request closed without merging**
