### PR TITLE
Add support for objects in sealed classes

### PR DESCRIPTION
**Pull request by tagantroy**
Hello, 
In our project we use combination of objects and data classes inside sealed classes to store some info as a type.
For example
```
sealed class PoolingStrategy {
    object Omni : PoolingStrategy()
    object ABI : PoolingStrategy()
    data class Combo(val list: List<PoolingStrategy>) : PoolingStrategy()
    object Manufacturer : PoolingStrategy()
    object Model : PoolingStrategy()
    object OperatingSystem : PoolingStrategy()
}
```
Only one data class inside and multiple objects, but objects were not supported.
This pull request adds support for objects inside sealed classes

### CODE REVIEW

**Review by sksamuel — APPROVED** [review]

**Comment by sksamuel** [comment]
Thanks. I'll merge once the test is fixed.

**Comment by sksamuel** [comment]
I'll roll this into 1.3.15 as well. I'll release that overnight.

**Comment by tagantroy** [comment]
@sksamuel Thank you :)

**Comment by sksamuel** [comment]
new version released

**Pull request merged**
