### PR TITLE
Do not treat quoted keys with dots as paths in TomlParser

### LINKED ISSUE #322: Maps & TOML: values for keys that contain dots are not decoded properly
The following code:

```kotlin
data class MapContainer(
    val myMap: Map<String, ExampleValue> = emptyMap()
)

data class ExampleValue(
    val number: Int = 9999
)

val toml = """
[myMap."twenty.two"]
number = 22
"""

val config = ConfigLoaderBuilder.default()
    .strict()
    .addPropertySource(TomlPropertySource(toml))
    .build()
    .loadConfigOrThrow<MapContainer>()

println(config)
```

Results in the following config object:

```
MapContainer(myMap={twenty.two=ExampleValue(number=9999)})
```

As you can see, the number value has been left to the default. If I don't put a default value at all in the `ExampleValue` data class, the code will crash reporting the `number` as missing:

```
Exception in thread "main" com.sksamuel.hoplite.ConfigException: Error loading config because:

    - Could not instantiate 'org.jetbrains.kotlin.idea.scratch.generated.ScratchFileRunnerGenerated.ScratchFileRunnerGenerated.MapContainer' because:

        - 'myMap': Collection element decode failure (:2:1):

            - Could not instantiate 'org.jetbrains.kotlin.idea.scratch.generated.ScratchFileRunnerGenerated.ScratchFileRunnerGenerated.ExampleValue' because:

                - 'number': Missing from config
	at com.sksamuel.hoplite.ConfigLoader$returnOrThrow$1.invoke(ConfigLoader.kt:192)
	at com.sksamuel.hoplite.ConfigLoader$returnOrThrow$1.invoke(ConfigLoader.kt:189)
	at com.sksamuel.hoplite.fp.ValidatedKt.getOrElse(Validated.kt:115)
	at com.sksamuel.hoplite.ConfigLoader.returnOrThrow(ConfigLoader.kt:189)
	at org.jetbrains.kotlin.idea.scratch.generated.ScratchFileRunnerGenerated$ScratchFileRunnerGenerated.<init>(tmp.kt:59)
	at org.jetbrains.kotlin.idea.scratch.generated.ScratchFileRunnerGenerated.main(tmp.kt:30)
```

What's a bit surprising is that the key's string is parsed properly, and only the value seems to be wrong. I'm not sure if this comes from TOMLJ, Hoplite or a bit of both, I'll try to investigate on my side.

(I cannot repro this when using YAML, only with TOML)

### PR DESCRIPTION
**Pull request by utybo**
Fixes #322 

- [x] Add failing test case
- [x] Investigate why it's not working
- [x] Provide fix

### CODE REVIEW

**Comment by utybo** [comment]
Seems that something is getting lost in the parsing process, as the values for keys that contain a dot are incorrect

image

**Comment by utybo** [comment]
I think I have a pretty good idea of why this doesn't work. TOMLJ's `isXxx(String)` functions actually parse the key as a dotted path (i.e. splits on the dots), whereas at this point we know that the key is the "entire key". This means that, because we are looking for `"twenty" -> "two"` when calling `isSomething`, which does not exist, we end up in the `else`, which is null (since `table.get(key)` will try to get `"twenty" -> "two"` instead of `"twenty.two"`).

image

**Comment by utybo** [comment]
I've pushed a fix, should be good now 👍🏻

**Comment by sksamuel** [comment]
Nice fix

**Comment by sksamuel** [comment]
2.3.3 is releasing

**Pull request merged**
