### PR TITLE
Added @ConfigAlias support

### LINKED ISSUE #197: @Alias annotation
Allow for a config value to be picked up from an alternative name.

### PR DESCRIPTION
**Pull request by sksamuel**
Closes #197

@jschneidereit

### CODE REVIEW

**Comment by sschuberth** [comment]
@sksamuel When can we expect a release with this?

**Comment by sksamuel** [comment]
It's already in 1.4.0 I think ?

**Comment by sschuberth** [comment]
Ah, I somehow missed that release, as on GitHub still version 1.3.15 is marked as the [latest release](https://github.com/sksamuel/hoplite/releases).

**Comment by sksamuel** [comment]
I hate that github releases thing as I always forget to update lol. I'll
correct shortly.

**Comment by sksamuel** [comment]
1.4.0 now latest release on GH.

**Pull request merged**
