### PR TITLE
Use shaded TomlJ library to avoid ANTLR version conflicts

### PR DESCRIPTION
**Pull request by ArtificialPB**
Solves the issue mentioned here: https://github.com/tomlj/tomlj/issues/29

### CODE REVIEW

**Comment by sksamuel** [comment]
I never like shading. What about just having a toml module where the toml dependency must be provided by the user. Then you can put in any version you want.

**Comment by ArtificialPB** [comment]
Can you give me an example on how the user would provide the dependency?

**Comment by sksamuel** [comment]
We could create a new hoplite-toml-runtime module, which compiles against tomlj but requires the user to provide the dependency.

**Comment by sksamuel** [comment]
Also, you can just override the version in gradle to any version you want. Is there a reason that won't work ?

**Comment by ArtificialPB** [comment]
Did it like you suggested but had to exclude the dependency from `hoplite-toml` module. 

Here's how I solved it, if anybody else needs it:
```kotlin
        api("com.sksamuel.hoplite:hoplite-toml:2.7.0") {
            exclude("org.tomlj", "tomlj")
        }
        implementation("org.tomlj:tomlj:1.1.0") {
            artifact {
                classifier = "all"
            }
        }
```

**Pull request closed without merging**
