### PR TITLE
Allow for uppercase only env var names

### PR DESCRIPTION
**Pull request by Globegitter**
Fix for further case mentioned in #77

As I mentioned in that issue, some shell environments are so restrictive that they only allow uppercase alphanumeric characters as well as underscores, so it would be nice if these environments could be supported by default.

So with `allowUppercaseNames` it checks if each environment starts with an uppercase character before it transforms them. This should then also keep backwards-compatibility. Alternatively, if such conditional transform could be confusing, it would also be possible to have a `enforceUppercaseNames` and throw if environment variables do not start in uppercase. What do you think?

### CODE REVIEW

**Comment by sksamuel** [comment]
I'm happy with if there's no edge cases that we're missing that would break things for current users.
Also the build is failing.

**Comment by Globegitter** [comment]
Ok, cool, then I will also look into adding a test and see why the build is failing.

**Comment by Globegitter** [comment]
@sksamuel Sorry it took so long but started to look into it now. I suppose we have uncovered an edge case. The test has `data class Test(val path: Path)` and in almost any environment there is an env var `PATH` already set of course and that is taking precedence. This is why the test is failing. So if we want full backwards-compatibility we would have to set `allowUppercaseNames` to `false` per default. What do you think?

**Comment by Globegitter** [comment]
I flipped now the default and added some tests. Let me know what you think.

**Comment by sksamuel** [comment]
I think default off makes sense so it's backwards compatible. We'd just need to update the docs.

**Pull request merged**
