### PR TITLE
Add default value handling for environment variable expressions.

### PR DESCRIPTION
**Pull request by mduesterhoeft**
With this change environment variable expressions can also have default values

`${USER:-default}`

### CODE REVIEW

**Comment by sksamuel** [comment]
This is great thanks!

**Comment by mduesterhoeft** [comment]
@sksamuel thanks - glad you like the idea - do you have plans already when to create a new release including this.

**Comment by sksamuel** [comment]
You could try the snapshot.
I'll do a proper release tonight.

**Comment by sksamuel** [comment]
Sorry for delay, 1.1.4 has been released.

**Pull request merged**
